# Generated by Django 5.0.7 on 2024-08-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_itmcolor_itmsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
